--
-- Procedures
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `GET_COMMON_MOVIES` (IN `FIRST_ACTOR_NAME` VARCHAR(128), IN `SECOND_ACTOR_NAME` VARCHAR(128))   BEGIN
	DECLARE FIRST_ACTOR_ID_VAR VARCHAR(16) DEFAULT "";
    DECLARE SECOND_ACTOR_ID_VAR VARCHAR(16) DEFAULT "";
    
	
    SELECT ID INTO FIRST_ACTOR_ID_VAR FROM ACTORS WHERE NAME = FIRST_ACTOR_NAME ;
    SELECT ID INTO SECOND_ACTOR_ID_VAR FROM ACTORS WHERE NAME = SECOND_ACTOR_NAME ;
    
    
    
    SELECT t1.MOVIE_ID
    FROM(
        SELECT MOVIE_ID
        FROM MOVIE_ACTORS
        WHERE ACTOR_ID=FIRST_ACTOR_ID_VAR
        ) t1
    INNER JOIN MOVIE_ACTORS t2
    ON t1.MOVIE_ID = t2.MOVIE_ID
    WHERE t2.ACTOR_ID=SECOND_ACTOR_ID_VAR;
        
    
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `GET_PLAYED_GENRES` (IN `ACTOR_NAME` VARCHAR(128))   BEGIN
	DECLARE ACTOR_ID_VAR VARCHAR(16) DEFAULT "";
    
	
    SELECT ID INTO ACTOR_ID_VAR FROM ACTORS WHERE NAME = ACTOR_NAME ;
    
      
    SELECT t1.GENRE as MOVIE_GENRE,
    COUNT(*) AS MOVIE_AMOUNT
    FROM MOVIES_GENRE t1
    INNER JOIN MOVIE_ACTORS t2
   	ON t1.ID = t2.MOVIE_ID
    WHERE t2.ACTOR_ID = ACTOR_ID_VAR
    GROUP BY MOVIE_GENRE;
    
END$$

DELIMITER ;

-- --------------------------------------------------------

